### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by shabeenabarde** [midoshawky/AutoCompleteTextField-Widget#1]
Is there a validation for this package so that it validates if its wrapped under the Form and warns if the field is missing.??

**Comment by midoshawky** [comment]
Actually this package was for just testing the pub but it seems that
there's some interest in it so i will make sure to make it validable thank
u for your notice

**Comment by shabeenabarde** [comment]
@midoshawky Thank you so much, I came across this package and it looked more easier to use then the rest. If possible can you also put other functions which are most used in a text field like Controller and focusNode?
